Repository testground/infra, pull requests merged in 2020-05, with the labels that each got.

#26 disable kube-metrics
  k8s/efs/manifest.yaml.spec
  k8s/install.sh
  k8s/kops-weave/dummy.yml
  k8s/prometheus-operator/values.yaml
  k8s/sidecar.yaml
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/cluster-bench.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/example-dash.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/k8s-api-server.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/k8s-kubelet.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/k8s-networking-cluster.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/k8s-networking-namespace-pods.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/k8s-networking-pod.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/k8s-stateful-sets.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/nodes.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/prometheus.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/redis.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/use-method-cluster.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/use-method-node.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/weavenet-cluster.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/weavenet.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/datasources/influxdb.json
  k8s/testground-infra/values.yaml
Labels: Approved, bug

#13 install influxdb
  k8s/cluster.yaml
  k8s/efs/manifest.yaml.spec
  k8s/influxdb/values.yaml
  k8s/install.sh
  k8s/kops-weave/dummy.yml
  k8s/prometheus-operator/values.yaml
  k8s/sidecar.yaml
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/cluster-bench.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/example-dash.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/k8s-api-server.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/k8s-kubelet.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/k8s-networking-cluster.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/k8s-networking-namespace-pods.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/k8s-networking-pod.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/k8s-stateful-sets.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/nodes.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/prometheus.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/redis.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/use-method-cluster.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/use-method-node.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/weavenet-cluster.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/weavenet.json
  k8s/testground-infra/values.yaml
Labels: Waiting for Review

#30 readme: add influxdata helm repo to instructions
  README.md
Labels: documentation

#32 configurable node types
  k8s/cluster.yaml
Labels: Approved, documentation, enhancement

#34 remove prometheus dashboards
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/cluster-bench.json
  k8s/testground-infra/charts/testground-dashboards/dashboards/dashboards/example-dash.json
Labels: Approved

#39 add provider aws
  k8s/testground-daemon/config-map-env-toml.yml
Labels: waiting for review

#40 add quotes to true labels
  k8s/cluster.yaml
Labels: waiting for review
